version: 2.1
orbs:
  rust: circleci/rust@1.1.1
jobs:
  lint-build-test:
        description: |
            Check linting with Clippy and rustfmt, build the crate, and run tests.
        executor:
            name: rust/default
            tag: 1.52.1
        steps:
            - checkout
            - restore_cache:
                keys:
                    - cargo-{{ checksum "Cargo.lock" }}-v1
            - run:
                name: Prepare for apt upgrades
                command: sudo apt update
            - run:
                name: Install libssl-dev for openssl-sys
                command: sudo apt install -y libssl-dev
            - run:
                name: Install libclang for rocksdb
                command: sudo apt install clang
            - run:
                name: Install rustfmt
                command: rustup component add rustfmt
            - run:
                name: Run rustfmt
                command: cargo fmt -- --check
            - rust/clippy:
                # Force a failure on clippy warnings
                flags: "-- --deny warnings"
                with_cache: false
            - rust/build:
                release: false
                with_cache: false
            - rust/test:
                with_cache: false
            - save_cache:
                key: cargo-{{ checksum "Cargo.lock" }}-v1
                paths:
                    - ~/.cargo
                    - target
workflows:
  merge-test:
    jobs:
      - lint-build-test
